#!/usr/bin/env python3

import RPi.GPIO as GPIO
import atexit, time

def cleanup():
    print("cleaning up...")
    GPIO.cleanup()

GPIO.setmode(GPIO.BCM)

GPIO.setup(17, GPIO.OUT)
GPIO.setup(14, GPIO.IN)

state = False
GPIO.output(17, 0)

atexit.register(cleanup)

def toggle_led(pin):
    global state
    print("got rising edge on", pin)
    state = not state
    GPIO.output(17, state)
       
    
GPIO.add_event_detect(14, GPIO.RISING, callback=toggle_led, bouncetime=200)

time.sleep(100000)
